server:
  port: 8888
spring:
  application:
    name: wuxin
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuxin_db?useSSL=false&serverTimezone=GMT%2b8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
  redis:
    host: 127.0.0.1
    database: 5
    port: 6379
    password:
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /*
  # 匹配链接
  urlPatterns: /admin/*